/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/webhook": {
    post: operations["receberMensagem"];
  };
  "/api/v1/auth/exchange": {
    /** Troca token de uso único por sessão (cookie HTTP-only) */
    post: operations["exchange"];
  };
  "/admin/api/v1/requisitantes/{id}/convite": {
    /** Gera link mágico de convite pra um requisitante */
    post: operations["gerarConvite"];
  };
  "/api/v1/resumo": {
    /** Resumo do mês: todos, pendentes e pagos — com filtros opcionais de mês e busca */
    get: operations["obter"];
  };
  "/api/v1/pedidos": {
    /** Lista pedidos do requisitante autenticado, com filtros e paginação */
    get: operations["listar"];
  };
  "/api/v1/pedidos/{id}": {
    /** Detalhe de um pedido específico */
    get: operations["buscar"];
  };
  "/api/v1/pedidos/{id}/foto-pedido": {
    /** Redireciona pra pre-signed URL da foto original do pedido */
    get: operations["fotoPedido"];
  };
  "/api/v1/pedidos/{id}/comprovante": {
    /** Redireciona pra pre-signed URL do comprovante do pedido */
    get: operations["comprovante"];
  };
  "/api/v1/auth/me": {
    /** Retorna o requisitante autenticado */
    get: operations["me"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Animation: {
      file_id?: string;
      file_unique_id?: string;
      /** Format: int32 */
      width?: number;
      /** Format: int32 */
      height?: number;
      /** Format: int32 */
      duration?: number;
      thumbnail?: components["schemas"]["PhotoSize"];
      file_name?: string;
      mime_type?: string;
      /** Format: int64 */
      file_size?: number;
    };
    Audio: {
      file_id?: string;
      file_unique_id?: string;
      /** Format: int32 */
      duration?: number;
      mime_type?: string;
      /** Format: int64 */
      file_size?: number;
      title?: string;
      performer?: string;
      thumbnail?: components["schemas"]["PhotoSize"];
      file_name?: string;
    };
    CallbackGame: Record<string, never>;
    CallbackQuery: {
      id?: string;
      from?: components["schemas"]["User"];
      message?: components["schemas"]["MaybeInaccessibleMessage"];
      inline_message_id?: string;
      data?: string;
      game_short_name?: string;
      chat_instance?: string;
    };
    Chat: {
      /** Format: int64 */
      id?: number;
      type?: string;
      title?: string;
      first_name?: string;
      last_name?: string;
      username?: string;
      photo?: components["schemas"]["ChatPhoto"];
      description?: string;
      invite_link?: string;
      pinned_message?: components["schemas"]["Message"];
      sticker_set_name?: string;
      can_set_sticker_set?: boolean;
      permissions?: components["schemas"]["ChatPermissions"];
      /** Format: int32 */
      slow_mode_delay?: number;
      bio?: string;
      /** Format: int64 */
      linked_chat_id?: number;
      location?: components["schemas"]["ChatLocation"];
      /** Format: int32 */
      message_auto_delete_time?: number;
      has_private_forwards?: boolean;
      has_protected_content?: boolean;
      join_to_send_messages?: boolean;
      join_by_request?: boolean;
      has_restricted_voice_and_video_messages?: boolean;
      is_forum?: boolean;
      active_usernames?: string[];
      emoji_status_custom_emoji_id?: string;
      has_aggressive_anti_spam_enabled?: boolean;
      has_hidden_members?: boolean;
      emoji_status_expiration_date?: boolean;
      available_reactions?: components["schemas"]["ReactionType"][];
      /** Format: int32 */
      accent_color_id?: number;
      background_custom_emoji_id?: string;
      profile_accent_color_id?: boolean;
      profile_background_custom_emoji_id?: string;
      has_visible_history?: boolean;
      /** Format: int32 */
      unrestrict_boost_count?: number;
      custom_emoji_sticker_set_name?: boolean;
    };
    ChatBoost: {
      boost_id?: string;
      /** Format: int32 */
      add_date?: number;
      /** Format: int32 */
      expiration_date?: number;
      source?: components["schemas"]["ChatBoostSource"];
    };
    ChatBoostAdded: {
      /** Format: int32 */
      boost_count?: number;
    };
    ChatBoostRemoved: {
      chat?: components["schemas"]["Chat"];
      boost_id?: string;
      /** Format: int32 */
      remove_date?: number;
      source?: components["schemas"]["ChatBoostSource"];
    };
    ChatBoostSource: Record<string, never>;
    ChatBoostUpdated: {
      chat?: components["schemas"]["Chat"];
      boost?: components["schemas"]["ChatBoost"];
    };
    ChatInviteLink: {
      invite_link?: string;
      creator?: components["schemas"]["User"];
      is_primary?: boolean;
      is_revoked?: boolean;
      /** Format: int32 */
      expire_date?: number;
      /** Format: int32 */
      member_limit?: number;
      name?: string;
      /** Format: int32 */
      pending_join_request_count?: number;
      creates_join_request?: boolean;
    };
    ChatJoinRequest: {
      chat?: components["schemas"]["Chat"];
      from?: components["schemas"]["User"];
      /** Format: int32 */
      date?: number;
      bio?: string;
      invite_link?: components["schemas"]["ChatInviteLink"];
      /** Format: int64 */
      user_chat_id?: number;
    };
    ChatLocation: {
      location?: components["schemas"]["Location"];
      address?: string;
    };
    ChatMember: {
      status?: string;
      user?: components["schemas"]["User"];
    };
    ChatMemberUpdated: {
      chat?: components["schemas"]["Chat"];
      from?: components["schemas"]["User"];
      /** Format: int32 */
      date?: number;
      old_chat_member?: components["schemas"]["ChatMember"];
      new_chat_member?: components["schemas"]["ChatMember"];
      invite_link?: components["schemas"]["ChatInviteLink"];
      via_chat_folder_invite_link?: boolean;
    };
    ChatPermissions: {
      can_send_messages?: boolean;
      can_send_audios?: boolean;
      can_send_documents?: boolean;
      can_send_photos?: boolean;
      can_send_videos?: boolean;
      can_send_video_notes?: boolean;
      can_send_voice_notes?: boolean;
      can_send_polls?: boolean;
      can_send_other_messages?: boolean;
      can_add_web_page_previews?: boolean;
      can_change_info?: boolean;
      can_invite_users?: boolean;
      can_pin_messages?: boolean;
      can_manage_topics?: boolean;
      /** @deprecated */
      can_send_media_messages?: boolean;
    };
    ChatPhoto: {
      small_file_id?: string;
      small_file_unique_id?: string;
      big_file_id?: string;
      big_file_unique_id?: string;
    };
    ChatShared: {
      request_id?: string;
      /** Format: int64 */
      chat_id?: number;
    };
    ChosenInlineQuery: {
      result_id?: string;
      from?: components["schemas"]["User"];
      location?: components["schemas"]["Location"];
      inline_message_id?: string;
      query?: string;
    };
    Contact: {
      phone_number?: string;
      first_name?: string;
      last_name?: string;
      /** Format: int64 */
      user_id?: number;
      vcard?: string;
    };
    Dice: {
      /** Format: int32 */
      value?: number;
      emoji?: string;
    };
    Document: {
      file_id?: string;
      file_unique_id?: string;
      thumbnail?: components["schemas"]["PhotoSize"];
      file_name?: string;
      mime_type?: string;
      /** Format: int64 */
      file_size?: number;
    };
    EncryptedCredentials: {
      data?: string;
      hash?: string;
      secret?: string;
    };
    EncryptedPassportElement: {
      type?: string;
      data?: string;
      phone_number?: string;
      email?: string;
      files?: components["schemas"]["PassportFile"][];
      front_side?: components["schemas"]["PassportFile"];
      reverse_side?: components["schemas"]["PassportFile"];
      selfie?: components["schemas"]["PassportFile"];
      translation?: components["schemas"]["PassportFile"][];
      hash?: string;
    };
    ExternalReplyInfo: {
      origin?: components["schemas"]["MessageOrigin"];
      chat?: components["schemas"]["Chat"];
      /** Format: int32 */
      message_id?: number;
      link_preview_options?: components["schemas"]["LinkPreviewOptions"];
      animation?: components["schemas"]["Animation"];
      audio?: components["schemas"]["Audio"];
      document?: components["schemas"]["Document"];
      photo?: components["schemas"]["PhotoSize"][];
      sticker?: components["schemas"]["Sticker"];
      story?: components["schemas"]["Story"];
      video?: components["schemas"]["Video"];
      video_note?: components["schemas"]["VideoNote"];
      voice?: components["schemas"]["Voice"];
      has_media_spoiler?: boolean;
      contact?: components["schemas"]["Contact"];
      dice?: components["schemas"]["Dice"];
      game?: components["schemas"]["Game"];
      giveaway?: components["schemas"]["Giveaway"];
      giveaway_winners?: components["schemas"]["GiveawayWinners"];
      invoice?: components["schemas"]["Invoice"];
      location?: components["schemas"]["Location"];
      poll?: components["schemas"]["Poll"];
      venue?: components["schemas"]["Venue"];
    };
    File: {
      file_id?: string;
      file_unique_id?: string;
      /** Format: int64 */
      file_size?: number;
      file_path?: string;
    };
    ForumTopicClosed: Record<string, never>;
    ForumTopicCreated: {
      name?: string;
      /** Format: int32 */
      icon_color?: number;
      icon_custom_emoji_id?: string;
    };
    ForumTopicEdited: {
      name?: string;
      icon_custom_emoji_id?: string;
    };
    ForumTopicReopened: Record<string, never>;
    Game: {
      title?: string;
      description?: string;
      photo?: components["schemas"]["PhotoSize"][];
      text?: string;
      text_entities?: components["schemas"]["MessageEntity"][];
      animation?: components["schemas"]["Animation"];
    };
    GeneralForumTopicHidden: Record<string, never>;
    GeneralForumTopicUnhidden: Record<string, never>;
    Giveaway: {
      chats?: components["schemas"]["Chat"][];
      /** Format: int32 */
      winners_selection_date?: number;
      /** Format: int32 */
      winner_count?: number;
      only_new_members?: boolean;
      has_public_winners?: boolean;
      prize_description?: string;
      country_codes?: string[];
      /** Format: int32 */
      premium_subscription_month_count?: number;
    };
    GiveawayCompleted: {
      /** Format: int32 */
      winner_count?: number;
      /** Format: int32 */
      unclaimed_prize_count?: number;
      giveaway_message?: components["schemas"]["Message"];
    };
    GiveawayCreated: Record<string, never>;
    GiveawayWinners: {
      chat?: components["schemas"]["Chat"];
      /** Format: int32 */
      giveaway_message_id?: number;
      /** Format: int32 */
      winners_selection_date?: number;
      /** Format: int32 */
      winner_count?: number;
      winners?: components["schemas"]["User"][];
      /** Format: int32 */
      additional_chat_count?: number;
      /** Format: int32 */
      premium_subscription_month_count?: number;
      /** Format: int32 */
      unclaimed_prize_count?: number;
      only_new_members?: boolean;
      was_refunded?: boolean;
      prize_description?: string;
    };
    InlineKeyboardButton: {
      text?: string;
      url?: string;
      callback_data?: string;
      callback_game?: components["schemas"]["CallbackGame"];
      switch_inline_query?: string;
      switch_inline_query_current_chat?: string;
      pay?: boolean;
      login_url?: components["schemas"]["LoginUrl"];
      web_app?: components["schemas"]["WebAppInfo"];
    };
    InlineKeyboardMarkup: {
      inline_keyboard?: components["schemas"]["InlineKeyboardButton"][][];
    };
    InlineQuery: {
      id?: string;
      from?: components["schemas"]["User"];
      location?: components["schemas"]["Location"];
      query?: string;
      offset?: string;
      chat_type?: string;
    };
    Invoice: {
      title?: string;
      description?: string;
      start_parameter?: string;
      currency?: string;
      /** Format: int32 */
      total_amount?: number;
      photo?: components["schemas"]["PhotoSize"];
    };
    LinkPreviewOptions: {
      is_disabled?: boolean;
      url?: string;
      prefer_small_media?: boolean;
      prefer_large_media?: boolean;
      show_above_text?: boolean;
    };
    Location: {
      /** Format: double */
      longitude?: number;
      /** Format: double */
      latitude?: number;
      /** Format: double */
      horizontal_accuracy?: number;
      /** Format: int32 */
      live_period?: number;
      /** Format: int32 */
      heading?: number;
      /** Format: int32 */
      proximity_alert_radius?: number;
    };
    LoginUrl: {
      url?: string;
      forward_text?: string;
      bot_username?: string;
      request_write_access?: boolean;
    };
    MaskPosition: {
      point?: string;
      /** Format: float */
      x_shift?: number;
      /** Format: float */
      y_shift?: number;
      /** Format: float */
      scale?: number;
    };
    MaybeInaccessibleMessage: {
      /** Format: int32 */
      date?: number;
      /** Format: int64 */
      chatId?: number;
      /** Format: int32 */
      messageId?: number;
      superGroupMessage?: boolean;
      userMessage?: boolean;
      groupMessage?: boolean;
    };
    Message: {
      /** Format: int32 */
      message_id?: number;
      /** Format: int32 */
      message_thread_id?: number;
      from?: components["schemas"]["User"];
      /** Format: int32 */
      date?: number;
      chat?: components["schemas"]["Chat"];
      forward_from?: components["schemas"]["User"];
      forward_from_chat?: components["schemas"]["Chat"];
      /** Format: int32 */
      forward_date?: number;
      text?: string;
      entities?: components["schemas"]["MessageEntity"][];
      caption_entities?: components["schemas"]["MessageEntity"][];
      audio?: components["schemas"]["Audio"];
      document?: components["schemas"]["Document"];
      photo?: components["schemas"]["PhotoSize"][];
      sticker?: components["schemas"]["Sticker"];
      video?: components["schemas"]["Video"];
      contact?: components["schemas"]["Contact"];
      location?: components["schemas"]["Location"];
      venue?: components["schemas"]["Venue"];
      animation?: components["schemas"]["Animation"];
      pinned_message?: components["schemas"]["MaybeInaccessibleMessage"];
      new_chat_members?: components["schemas"]["User"][];
      left_chat_member?: components["schemas"]["User"];
      new_chat_title?: string;
      new_chat_photo?: components["schemas"]["PhotoSize"][];
      delete_chat_photo?: boolean;
      group_chat_created?: boolean;
      reply_to_message?: components["schemas"]["Message"];
      voice?: components["schemas"]["Voice"];
      caption?: string;
      supergroup_chat_created?: boolean;
      channel_chat_created?: boolean;
      /** Format: int64 */
      migrate_to_chat_id?: number;
      /** Format: int64 */
      migrate_from_chat_id?: number;
      /** Format: int32 */
      edit_date?: number;
      game?: components["schemas"]["Game"];
      /** Format: int32 */
      forward_from_message_id?: number;
      invoice?: components["schemas"]["Invoice"];
      successful_payment?: components["schemas"]["SuccessfulPayment"];
      video_note?: components["schemas"]["VideoNote"];
      author_signature?: string;
      forward_signature?: string;
      media_group_id?: string;
      connected_website?: string;
      passport_data?: components["schemas"]["PassportData"];
      forward_sender_name?: string;
      poll?: components["schemas"]["Poll"];
      reply_markup?: components["schemas"]["InlineKeyboardMarkup"];
      dice?: components["schemas"]["Dice"];
      via_bot?: components["schemas"]["User"];
      sender_chat?: components["schemas"]["Chat"];
      proximity_alert_triggered?: components["schemas"]["ProximityAlertTriggered"];
      message_auto_delete_timer_changed?: components["schemas"]["MessageAutoDeleteTimerChanged"];
      is_automatic_forward?: boolean;
      has_protected_content?: boolean;
      web_app_data?: components["schemas"]["WebAppData"];
      video_chat_started?: components["schemas"]["VideoChatStarted"];
      video_chat_ended?: components["schemas"]["VideoChatEnded"];
      video_chat_participants_invited?: components["schemas"]["VideoChatParticipantsInvited"];
      video_chat_scheduled?: components["schemas"]["VideoChatScheduled"];
      is_topic_message?: boolean;
      forum_topic_created?: components["schemas"]["ForumTopicCreated"];
      forum_topic_closed?: components["schemas"]["ForumTopicClosed"];
      forum_topic_reopened?: components["schemas"]["ForumTopicReopened"];
      forum_topic_edited?: components["schemas"]["ForumTopicEdited"];
      general_forum_topic_hidden?: components["schemas"]["GeneralForumTopicHidden"];
      general_forum_topic_unhidden?: components["schemas"]["GeneralForumTopicUnhidden"];
      write_access_allowed?: components["schemas"]["WriteAccessAllowed"];
      has_media_spoiler?: boolean;
      user_shared?: components["schemas"]["UserShared"];
      chat_shared?: components["schemas"]["ChatShared"];
      story?: components["schemas"]["Story"];
      external_reply?: components["schemas"]["ExternalReplyInfo"];
      forward_origin?: components["schemas"]["MessageOrigin"];
      link_preview_options?: components["schemas"]["LinkPreviewOptions"];
      quote?: components["schemas"]["TextQuote"];
      users_shared?: components["schemas"]["UsersShared"];
      giveaway_created?: components["schemas"]["GiveawayCreated"];
      giveaway?: components["schemas"]["Giveaway"];
      giveaway_winners?: components["schemas"]["GiveawayWinners"];
      giveaway_completed?: components["schemas"]["GiveawayCompleted"];
      reply_to_story?: components["schemas"]["Story"];
      boost_added?: components["schemas"]["ChatBoostAdded"];
      /** Format: int32 */
      sender_boost_count?: number;
    };
    MessageAutoDeleteTimerChanged: {
      /** Format: int32 */
      message_auto_delete_time?: number;
    };
    MessageEntity: {
      type?: string;
      /** Format: int32 */
      offset?: number;
      /** Format: int32 */
      length?: number;
      url?: string;
      user?: components["schemas"]["User"];
      language?: string;
      custom_emoji_id?: string;
    };
    MessageOrigin: Record<string, never>;
    MessageReactionCountUpdated: {
      chat?: components["schemas"]["Chat"];
      /** Format: int32 */
      message_id?: number;
      /** Format: int32 */
      date?: number;
      reactions?: components["schemas"]["ReactionCount"][];
    };
    MessageReactionUpdated: {
      chat?: components["schemas"]["Chat"];
      /** Format: int32 */
      message_id?: number;
      user?: components["schemas"]["User"];
      actor_chat?: components["schemas"]["Chat"];
      /** Format: int32 */
      date?: number;
      old_reaction?: components["schemas"]["ReactionType"][];
      new_reaction?: components["schemas"]["ReactionType"][];
    };
    OrderInfo: {
      name?: string;
      phone_number?: string;
      email?: string;
      shipping_address?: components["schemas"]["ShippingAddress"];
    };
    PassportData: {
      data?: components["schemas"]["EncryptedPassportElement"][];
      credentials?: components["schemas"]["EncryptedCredentials"];
    };
    PassportFile: {
      file_id?: string;
      file_unique_id?: string;
      /** Format: int32 */
      file_size?: number;
      /** Format: int32 */
      file_date?: number;
    };
    PhotoSize: {
      file_id?: string;
      file_unique_id?: string;
      /** Format: int32 */
      width?: number;
      /** Format: int32 */
      height?: number;
      /** Format: int32 */
      file_size?: number;
      file_path?: string;
    };
    Poll: {
      id?: string;
      question?: string;
      options?: components["schemas"]["PollOption"][];
      /** Format: int32 */
      total_voter_count?: number;
      is_closed?: boolean;
      is_anonymous?: boolean;
      type?: string;
      allows_multiple_answers?: boolean;
      /** Format: int32 */
      correct_option_id?: number;
      /** Format: int32 */
      open_period?: number;
      /** Format: int32 */
      close_date?: number;
      explanation?: string;
      explanation_entities?: components["schemas"]["MessageEntity"][];
    };
    PollAnswer: {
      poll_id?: string;
      user?: components["schemas"]["User"];
      option_ids?: number[];
      voter_chat?: components["schemas"]["Chat"];
    };
    PollOption: {
      text?: string;
      /** Format: int32 */
      voter_count?: number;
    };
    PreCheckoutQuery: {
      id?: string;
      from?: components["schemas"]["User"];
      currency?: string;
      /** Format: int32 */
      total_amount?: number;
      invoice_payload?: string;
      shipping_option_id?: string;
      order_info?: components["schemas"]["OrderInfo"];
    };
    ProximityAlertTriggered: {
      traveler?: components["schemas"]["User"];
      watcher?: components["schemas"]["User"];
      /** Format: int32 */
      distance?: number;
    };
    ReactionCount: {
      type?: components["schemas"]["ReactionType"];
      /** Format: int32 */
      total_count?: number;
    };
    ReactionType: Record<string, never>;
    ShippingAddress: {
      country_code?: string;
      state?: string;
      city?: string;
      street_line1?: string;
      street_line2?: string;
      post_code?: string;
    };
    ShippingQuery: {
      id?: string;
      from?: components["schemas"]["User"];
      invoice_payload?: string;
      shipping_address?: components["schemas"]["ShippingAddress"];
    };
    Sticker: {
      file_id?: string;
      file_unique_id?: string;
      type?: string;
      /** Format: int32 */
      width?: number;
      /** Format: int32 */
      height?: number;
      thumbnail?: components["schemas"]["PhotoSize"];
      /** Format: int32 */
      file_size?: number;
      emoji?: string;
      set_name?: string;
      mask_position?: components["schemas"]["MaskPosition"];
      is_animated?: boolean;
      is_video?: boolean;
      premium_animation?: components["schemas"]["File"];
      custom_emoji_id?: string;
      needs_repainting?: boolean;
    };
    Story: {
      chat?: components["schemas"]["Chat"];
      /** Format: int32 */
      id?: number;
    };
    SuccessfulPayment: {
      currency?: string;
      /** Format: int32 */
      total_amount?: number;
      invoice_payload?: string;
      shipping_option_id?: string;
      order_info?: components["schemas"]["OrderInfo"];
      telegram_payment_charge_id?: string;
      provider_payment_charge_id?: string;
    };
    TextQuote: {
      text?: string;
      entities?: components["schemas"]["MessageEntity"][];
      /** Format: int32 */
      position?: number;
      is_manual?: boolean;
    };
    Update: {
      /** Format: int32 */
      update_id?: number;
      message?: components["schemas"]["Message"];
      inline_query?: components["schemas"]["InlineQuery"];
      chosen_inline_result?: components["schemas"]["ChosenInlineQuery"];
      callback_query?: components["schemas"]["CallbackQuery"];
      edited_message?: components["schemas"]["Message"];
      channel_post?: components["schemas"]["Message"];
      edited_channel_post?: components["schemas"]["Message"];
      shipping_query?: components["schemas"]["ShippingQuery"];
      pre_checkout_query?: components["schemas"]["PreCheckoutQuery"];
      poll?: components["schemas"]["Poll"];
      poll_answer?: components["schemas"]["PollAnswer"];
      my_chat_member?: components["schemas"]["ChatMemberUpdated"];
      chat_member?: components["schemas"]["ChatMemberUpdated"];
      chat_join_request?: components["schemas"]["ChatJoinRequest"];
      message_reaction?: components["schemas"]["MessageReactionUpdated"];
      message_reaction_count?: components["schemas"]["MessageReactionCountUpdated"];
      chat_boost?: components["schemas"]["ChatBoostUpdated"];
      removed_chat_boost?: components["schemas"]["ChatBoostRemoved"];
    };
    User: {
      /** Format: int64 */
      id?: number;
      first_name?: string;
      is_bot?: boolean;
      last_name?: string;
      username?: string;
      language_code?: string;
      can_join_groups?: boolean;
      can_read_all_group_messages?: boolean;
      supports_inline_queries?: boolean;
      is_premium?: boolean;
      added_to_attachment_menu?: boolean;
    };
    UserShared: {
      request_id?: string;
      /** Format: int64 */
      user_id?: number;
    };
    UsersShared: {
      request_id?: string;
      user_ids?: number[];
    };
    Venue: {
      location?: components["schemas"]["Location"];
      title?: string;
      address?: string;
      foursquare_id?: string;
      foursquare_type?: string;
      google_place_id?: string;
      google_place_type?: string;
    };
    Video: {
      file_id?: string;
      file_unique_id?: string;
      /** Format: int32 */
      width?: number;
      /** Format: int32 */
      height?: number;
      /** Format: int32 */
      duration?: number;
      thumbnail?: components["schemas"]["PhotoSize"];
      mime_type?: string;
      /** Format: int64 */
      file_size?: number;
      file_name?: string;
    };
    VideoChatEnded: {
      /** Format: int32 */
      duration?: number;
    };
    VideoChatParticipantsInvited: {
      users?: components["schemas"]["User"][];
    };
    VideoChatScheduled: {
      /** Format: int32 */
      start_date?: number;
    };
    VideoChatStarted: Record<string, never>;
    VideoNote: {
      file_id?: string;
      file_unique_id?: string;
      /** Format: int32 */
      length?: number;
      /** Format: int32 */
      duration?: number;
      thumbnail?: components["schemas"]["PhotoSize"];
      /** Format: int32 */
      file_size?: number;
    };
    Voice: {
      file_id?: string;
      file_unique_id?: string;
      /** Format: int32 */
      duration?: number;
      mime_type?: string;
      /** Format: int64 */
      file_size?: number;
    };
    WebAppData: {
      data?: string;
      button_text?: string;
    };
    WebAppInfo: {
      url?: string;
    };
    WriteAccessAllowed: {
      from_request?: boolean;
      web_app_name?: string;
      from_attachment_menu?: boolean;
    };
    /** @description Token de uso único recebido via link mágico */
    AuthExchangeRequest: {
      /**
       * @description Token gerado pelo admin, recebido como query param ?t=
       * @example ABCdef123...
       */
      token: string;
    };
    /** @description Resposta dos endpoints de autenticação (/auth/exchange e /auth/me) */
    AuthMeResponse: {
      requisitante?: components["schemas"]["RequisitanteDTO"];
    };
    /** @description Dados do requisitante autenticado */
    RequisitanteDTO: {
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example Pedro Marques */
      nome?: string;
    };
    GerarConviteResponse: {
      url?: string;
    };
    /** @description Resumo de um mês: contagem e total por status (todos, pendentes, pagos) */
    ResumoMesDTO: {
      /**
       * @description Mês de referência no formato YYYY-MM
       * @example 2026-05
       */
      mes?: string;
      todos?: components["schemas"]["ResumoStatusDTO"];
      pendentes?: components["schemas"]["ResumoStatusDTO"];
      pagos?: components["schemas"]["ResumoStatusDTO"];
    };
    /** @description Agregado de pedidos por status (quantidade + total) */
    ResumoStatusDTO: {
      /**
       * Format: int32
       * @example 3
       */
      quantidade?: number;
      /** @example 7230 */
      total?: number;
    };
    /** @description Wrapper genérico de página com paginação */
    PaginaDTOPedidoResumoDTO: {
      /** @description Itens da página atual */
      items?: components["schemas"]["PedidoResumoDTO"][];
      /**
       * Format: int64
       * @description Total de itens encontrados (em todas as páginas)
       * @example 142
       */
      total?: number;
      /**
       * Format: int32
       * @description Página atual (0-indexed)
       * @example 0
       */
      pagina?: number;
      /**
       * Format: int32
       * @description Tamanho de página solicitado
       * @example 20
       */
      tamanho?: number;
      /**
       * Format: int32
       * @description Total de páginas
       * @example 8
       */
      totalPaginas?: number;
    };
    /** @description Resumo de um pedido pra listagem */
    PedidoResumoDTO: {
      /**
       * Format: int64
       * @description ID único do pedido
       * @example 142
       */
      id?: number;
      /**
       * @description Valor em reais
       * @example 287.5
       */
      valor?: number;
      /**
       * @description Descrição livre do pedido
       * @example Boleto energia
       */
      descricao?: string;
      /**
       * @description Tipo de pagamento
       * @enum {string}
       */
      tipo?: "BOLETO" | "PIX" | "TED" | "AGENDAMENTO" | "OUTRO";
      /**
       * @description Status atual do pedido
       * @enum {string}
       */
      status?: "PENDENTE" | "PAGO" | "CANCELADO";
      /**
       * Format: date
       * @description Data em que o pedido foi solicitado
       * @example 2026-05-03
       */
      dataPedido?: string;
      /**
       * Format: date
       * @description Data em que o pagamento foi efetuado (null se PENDENTE)
       * @example 2026-05-04
       */
      dataPagamento?: string | null;
      /**
       * @description Existe um comprovante anexado a este pedido?
       * @example true
       */
      temComprovante?: boolean;
    };
    /** @description Detalhes completos de um pedido */
    PedidoDetalheDTO: {
      /**
       * Format: int64
       * @example 142
       */
      id?: number;
      /** @example 287.5 */
      valor?: number;
      /** @example Boleto energia */
      descricao?: string;
      /** @enum {string} */
      tipo?: "BOLETO" | "PIX" | "TED" | "AGENDAMENTO" | "OUTRO";
      /** @enum {string} */
      status?: "PENDENTE" | "PAGO" | "CANCELADO";
      /**
       * Format: date
       * @example 2026-05-03
       */
      dataPedido?: string;
      /**
       * Format: date
       * @example 2026-05-04
       */
      dataPagamento?: string | null;
      /** @description Existe comprovante? */
      temComprovante?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  receberMensagem: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Update"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  /** Troca token de uso único por sessão (cookie HTTP-only) */
  exchange: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthExchangeRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AuthMeResponse"];
        };
      };
    };
  };
  /** Gera link mágico de convite pra um requisitante */
  gerarConvite: {
    parameters: {
      header?: {
        "X-Admin-Key"?: string;
      };
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["GerarConviteResponse"];
        };
      };
    };
  };
  /** Resumo do mês: todos, pendentes e pagos — com filtros opcionais de mês e busca */
  obter: {
    parameters: {
      query?: {
        /**
         * @description Mês no formato YYYY-MM. Default: mês corrente.
         * @example 2026-05
         */
        mes?: string;
        /**
         * @description Filtra por texto na descrição (contém, case-insensitive).
         * @example boleto
         */
        busca?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResumoMesDTO"];
        };
      };
    };
  };
  /** Lista pedidos do requisitante autenticado, com filtros e paginação */
  listar: {
    parameters: {
      query?: {
        status?: string;
        tipo?: ("BOLETO" | "PIX" | "TED" | "AGENDAMENTO" | "OUTRO")[];
        de?: string;
        ate?: string;
        busca?: string;
        page?: number;
        tamanho?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PaginaDTOPedidoResumoDTO"];
        };
      };
    };
  };
  /** Detalhe de um pedido específico */
  buscar: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PedidoDetalheDTO"];
        };
      };
    };
  };
  /** Redireciona pra pre-signed URL da foto original do pedido */
  fotoPedido: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  /** Redireciona pra pre-signed URL do comprovante do pedido */
  comprovante: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  /** Retorna o requisitante autenticado */
  me: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AuthMeResponse"];
        };
      };
    };
  };
}
